Import('qt_env')

env = qt_env.Clone()

env.EnableQtModules('Core')

env.AppendUnique(CPPDEFINES = [
    '_UNICODE',
    '_CRT_SECURE_NO_WARNINGS'
])

env.AppendUnique(LIBS = 'advapi32')

env['MANIFEST_UAC'] =\
    '/MANIFESTUAC:"' + ' '.join(("level='requireAdministrator'",
                                 "uiAccess='false'")) + '"'

env.AppendUnique(LINKFLAGS = [
    '/SUBSYSTEM:CONSOLE',
    '${MANIFEST_UAC}',
    '${EXE_MANIFEST_DEPENDENCY}'
])

prog = env.Program('helper', env.Glob('*.cpp'))

env.InstallModule(prog)

res = env['QT_USED_MODULES']
Return('res')
